const lyrics = [
    { time: 0.61, text: "無敵の笑顔で荒らすメディア", romaji: "Muteki no egao de arasu media" },
    { time: 3.32, text: "知りたいその秘密ミステリアス", romaji: "Shiritai sono himitsu misuteriasu" },
    { time: 5.92, text: "抜けてるとこさえ彼女のエリア", romaji: "Nuketeru toko sae kanojo no eria" },
    { time: 9.10, text: "完璧で嘘つきな君は", romaji: "Kanpeki de usotsuki na kimi wa" },
    { time: 11.89, text: "天才的なアイドル様", romaji: "Tensaitekina aidoru sama" },
    { time: 14.76, text: "(You're my savior, you're my saving grace)", romaji: "" },
    { time: 17.26, text: "今日何食べた？", romaji: "Kyou nani tabeta?" },
    { time: 18.74, text: "好きな本は？", romaji: "Suki na hon wa?" },
    { time: 20.31, text: "遊びに行くならどこに行くの？", romaji: "Asobi ni iku nara doko ni iku no?" },
    { time: 23.07, text: "何も食べてない", romaji: "Nanimo tabetenai" },
    { time: 24.61, text: "それは内緒", romaji: "Sore wa naisho" },
    { time: 26.12, text: "何を聞かれても", romaji: "Nani wo kikaretemo" },
    { time: 27.64, text: "のらりくらり", romaji: "Norari kurari" },
    { time: 28.74, text: "そう淡々と", romaji: "Sou tantan to" },
    { time: 30.01, text: "だけど燦々と", romaji: "Dakedo sansan to" },
    { time: 31.55, text: "見えそうで見えない秘密は蜜の味", romaji: "Miesou de mienai himitsu wa mitsu no aji" },
    { time: 34.58, text: "あれもないないない", romaji: "Are mo nai, nai, nai" },
    { time: 35.73, text: "これもないないない", romaji: "Kore mo nai, nai, nai" },
    { time: 37.26, text: "好きなタイプは？", romaji: "Suki na taipu wa?" },
    { time: 38.55, text: "相手は？", romaji: "Aite wa?" },
    { time: 39.19, text: "さあ答えて", romaji: "Saa kotaete" },
    { time: 40.23, text: "「誰かを好きになることなんて私分からなくてさ」", romaji: "\"Dareka wo suki ni naru koto nante watashi wakaranakute sa\"" },
    { time: 46.16, text: "嘘か本当か知り得ない", romaji: "Uso ka hontou ka shirienai" },
    { time: 48.97, text: "そんな言葉にまた一人堕ちる", romaji: "Sonna kotoba ni mata hitori ochiru" },
    { time: 52.85, text: "また好きにさせる", romaji: "Mata suki ni saseru" },
    { time: 54.76, text: "誰もが目を奪われていく", romaji: "Daremo ga me wo ubawareteiku" },
    { time: 57.70, text: "君は完璧で究極のアイドル", romaji: "Kimi wa kanpeki de kyuukyoku no aidoru" },
    { time: 60.97, text: "金輪際現れない", romaji: "Konrinzai arawarenai" },
    { time: 63.43, text: "一番星の生まれ変わり", romaji: "Ichiban boshi no umarekawari" },
    { time: 66.40, text: "ああ その笑顔で愛してるで", romaji: "Aa, sono egao de aishiteru de" },
    { time: 69.98, text: "誰も彼も虜にしていく", romaji: "Daremo kare mo toriko ni shite iku" },
    { time: 72.95, text: "その瞳がその言葉が", romaji: "Sono hitomi ga sono kotoba ga" },
    { time: 75.32, text: "嘘でもそれは完全なアイ", romaji: "Uso demo sore wa kanzen na ai" },
    { time: 78.51, text: "はいはいあの子は特別です", romaji: "Hai, hai, ano ko wa tokubetsu desu" },
    { time: 81.46, text: "我々はハナからおまけです", romaji: "Wareware wa hana kara omake desu" },
    { time: 84.11, text: "お星様の引き立て役Bです", romaji: "Ohoshi sama no hikitateyaku B desu" },
    { time: 87.37, text: "全てがあの子のお陰なわけない", romaji: "Subete ga ano ko no okagena wake nai" },
    { time: 90.21, text: "洒落臭い", romaji: "Sharakusai" },
    { time: 91.06, text: "妬み嫉妬なんてないわけがない", romaji: "Netami shitto nante nai wake ga nai" },
    { time: 93.28, text: "これはネタじゃない", romaji: "Kore wa neta janai" },
    { time: 94.29, text: "からこそ許せない", romaji: "Kara koso yurusenai" },
    { time: 95.37, text: "完璧じゃない君じゃ許せない", romaji: "Kanpeki janai kimi ja yurusenai" },
    { time: 97.30, text: "自分を許せない", romaji: "Jibun wo yurusenai" },
    { time: 98.43, text: "誰よりも強い君以外は認めない", romaji: "Dare yori mo tsuyoi kimi igai wa mitomenai" },
    { time: 101.01, text: "誰もが信じ崇めてる", romaji: "Daremo ga shinji agameteru" },
    { time: 104.01, text: "まさに最強で無敵のアイドル", romaji: "Masani saikyou de muteki no aidoru" },
    { time: 107.28, text: "弱点なんて見当たらない", romaji: "Jakuten nante miataranai" },
    { time: 109.60, text: "一番星を宿している", romaji: "Ichiban boshi wo yado shiteiru" },
    { time: 112.85, text: "弱いとこなんて見せちゃダメダメ", romaji: "Yowai toko nante misecha dame, dame" },
    { time: 115.85, text: "知りたくないとこは見せずに", romaji: "Shiritakunai toko wa misezu ni" },
    { time: 118.85, text: "唯一無二じゃなくちゃイヤイヤ", romaji: "Yuiitsumuni janakucha iya, iya" },
    { time: 121.65, text: "それこそ本物のアイ", romaji: "Sorekoso honmono no ai" },
    { time: 125.18, text: "得意の笑顔で沸かすメディア", romaji: "Tokui no egao de wakasu media" },
    { time: 128.32, text: "隠しきるこの秘密だけは", romaji: "Kakushikiru kono himitsu dake wa" },
    { time: 131.02, text: "愛してるって嘘で積むキャリア", romaji: "Aishiteru tte uso de tsumu kyaria" },
    { time: 134.63, text: "これこそ私なりの愛だ", romaji: "Korekoso watashi nari no ai da" },
    { time: 137.99, text: "流れる汗も綺麗なアクア", romaji: "Nagareru ase mo kireina Aqua" },
    { time: 140.93, text: "ルビーを隠したこの瞼", romaji: "Rubii wo kakushita kono mabuta" },
    { time: 143.80, text: "歌い踊り舞う私はマリア", romaji: "Utai odori mau watashi wa maria" },
    { time: 147.32, text: "そう嘘はとびきりの愛だ", romaji: "Sou uso wa tobikiri no ai da" },
    { time: 151.33, text: "誰かに愛されたことも", romaji: "Dareka ni aisareta koto mo" },
    { time: 154.58, text: "誰かのこと愛したこともない", romaji: "Dareka no koto aishita koto mo nai" },
    { time: 157.97, text: "そんな私の嘘がいつか本当になること", romaji: "Sonna watashi no uso ga itsuka hontou ni naru koto" },
    { time: 163.65, text: "（信じてる）", romaji: "(Shinjiteru)" },
    { time: 164.79, text: "いつかきっと全部手に入れる", romaji: "Itsuka kitto zenbu te ni ireru" },
    { time: 167.93, text: "私はそう欲張りなアイドル", romaji: "Watashi wa sou yokubarina aidoru" },
    { time: 171.17, text: "等身大でみんなのこと", romaji: "Toushindai de minna no koto" },
    { time: 173.76, text: "ちゃんと愛したいから", romaji: "Chanto aishitai kara" },
    { time: 176.55, text: "今日も嘘をつくの", romaji: "Kyou mo uso wo tsuku no" },
    { time: 179.03, text: "この言葉がいつか本当になる日を願って", romaji: "Kono kotoba ga itsuka hontou ni naru hi wo negatte" },
    { time: 183.25, text: "それでもまだ", romaji: "Sore demo mada" },
    { time: 184.74, text: "君と君にだけは言えずにいたけど", romaji: "Kimi to kimi ni dake wa iezu ni ita kedo" },
    { time: 188.50, text: "ああ やっと言えた", romaji: "Ah, yatto ieta" },
    { time: 190.66, text: "これは絶対嘘じゃない", romaji: "Kore wa zettai uso janai" },
    { time: 192.77, text: "愛してる", romaji: "Aishiteru" },
    { time: 195.66, text: "[Instrumental]", romaji: "" },
    { time: 205.91, text: "(You're my savior, my true savior, my saving grace)", romaji: "" },
    { time: 209.63, text: "[Song Ending]", romaji: "" },
];
